[package]
name = "dwin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = { version = "3.0.1", optional = true }
heapless = "0.8.0"

[dev-dependencies]
criterion = "0.5.1"

[features]
default = ["crc"]
crc = ["dep:crc"]

[[bench]]
name = "benchmarks"
harness = false

[lib]
bench = false
