[package]
name = "dwin"
version = "0.0.0"
authors = ["Süha ÜNÜVAR"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/phycrax/dwin-rs"
description = "A no_std + serde based DWIN DGUS2 library for Rust"
license = "MIT OR Apache-2.0"
categories = ["embedded", "no-std"]
keywords = ["dwin", "dgus"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
crc = { version = "3.0.1" }
defmt = { version = "0.3", optional = true }
heapless = { version = "0.8.0", default-features = false, optional = true }

[dev-dependencies]
criterion = "0.5.1"

[features]
default = ["heapless"]
defmt = ["dep:defmt"]
heapless = ["dep:heapless"]

[[bench]]
name = "benchmarks"
harness = false

[lib]
bench = false
