[package]
name = "dwin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = { version = "3.0.1", optional = true }
defmt = { version = "0.3.6", optional = true }

[dev-dependencies]
criterion = "0.5.1"

[features]
default = ["crc"]
crc = ["dep:crc"]
defmt = ["dep:defmt"]

[[bench]]
name = "benchmarks"
harness = false

[lib]
bench = false
