[package]
name = "dwin"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }
crc = { version = "3.0.1" }
defmt = { version = "0.3", optional = true }
heapless = { version = "0.8.0", default-features = false, optional = true }

[dev-dependencies]
criterion = "0.5.1"

[features]
default = ["heapless"]
defmt = ["dep:defmt"]
heapless = ["dep:heapless"]

[[bench]]
name = "benchmarks"
harness = false

[lib]
bench = false
